### ISSUE TITLE
Correlating Stretch Direction and Strain

### ISSUE THREAD

**Issue by vc0147** [MultiDIC/MultiDIC#11]
Hello Dana,

I've been having some troubles understanding how the principal stretch are plotted, and how those relate to the principal strains. Below is a picture of a specimen (shown on the tension side) being curved. How are the stretch lines plotted? I thought it might be from the [U,V,W] vector, but that doesn't make sense for the "2nd Principal Stretch" image. Also, the strains that I get from the 1st principal stretch is negative. Unless your sign convention is positive equals compression, I don't understand why the results show negative strains when the specimen is stretched horizontally from the curvature. 

Please do advice! Thank you in advance!

Best, Vivian

![Capture](https://user-images.githubusercontent.com/48099344/63543024-a4e49500-c4d6-11e9-8e1f-62096827bb8b.JPG)

**Comment by danasolav** [comment]
Hi Vivian, 

Sorry for the late reply.

The 1st and 2nd principal stretches are the 2 eigenvalues of the deformation tensor, and their corresponding eigenvectors are the directions on the surface plane. Normally, if you stretch a material in one direction it will compress in the orthogonal direction. Hence, the 1st stretch is <1 (compression) and the 2nd is >1 (tension). They are always sorted from small to large, so 1st doesn't mean it has the largest absolute value. In your case, if you're interested in the tensile stretch, you should look at the 2nd principal stretch/strain. The principal directions represent the lines along which the material experiences the smallest and largest stretches.

I don't understand what do you mean by "shown on the tension side" and "stretched horizontally from the curvature". Can you explain what test did you perform and attach the raw image you analyzed, if you can?

Thanks,
Dana

**Comment by vc0147** [comment]
Hello Dana,

Thank you for replying so thoroughly! I have attached a GIF of what test I did. Essentially, it is pulling the edges of a strip of material around a known radius (configured by the bolts). What I mean with "tension side" is that the images are taken on the tension side of the bended strip.  That's why I expect there to be a horizontal tensile stress instead of what's shown in the 2nd principal stretch/strain image above. 

Also, could I clarify: The principal strains stored are the max strains on the element (in tension & compression), but that doesn't necessarily mean they are the local strains, ε_xx & ε_yy on the specimen. In order to obtain the local strains, the principal strains will need to be transformed?

Thank you,
Vivian

![39a467](https://user-images.githubusercontent.com/48099344/64033950-71bb8a80-cb02-11e9-9408-75af096a747c.gif)

**Comment by danasolav** [comment]
Hi Vivian,

Beginning with your second question: that's correct, the principal strains are the min/max strains on each element. Their directions are given in the global coordinate system which is defined during the calibration step. If you're interested in the xx and yy strains, you can extract them from the strain tensors. These would be the (1,1) and (2,2) components of the strain tensor. The x and y directions are the global directions of the coordinate system, defined in STEP1 from your calibration object. Therefore, these strains might not be planar on your sample in all points, and might be meaningless. These are NOT local variable planar x and y directions. MultiDIC doesn't provide these strains because they're not uniquely defined for each problem. On a cylindrical sample it might make sense to define local axial and circumferential directions, but on a sample with arbitrary 3D geometry, these directions are not easily defined. However, if you want to extract the strains in a local coordinate system that you defined for your test, you can do it by taking the 3D strain tensors and project them on these directions. The direction normal to the element plane is stored as "d3", so if you multiply the strain tensor by d3 you get a "strain vector" which you can then separate into any two orthogonal directions.

Regarding the results you got- it does seem odd. Could you send me the final results mat file (DIC3DPPresults) so I can have a look at it? You can email to danask@mit.edu.

Additionally, I just wanted to note that your speckle pattern is not dense enough. The black-white ratio should be ~50%, and you have much more white. It couldn't cause the above mentioned problem, but you might want to improve it in the future to get more accurate results.

Thanks,
Dana
