### ISSUE TITLE
some questions about MultiDIC toolbox

### ISSUE THREAD

**Issue by shanchao0906** [MultiDIC/MultiDIC#14]
Hi Dana,
The toolbox you designed is very useful, but I have some questions to ask you
1. How to modify step 1 after the stereo calibration object is changed to the checkerboard；
2. Whether the speckle map can be manually used, such as drawing black spots randomly on the white paper with a black pen and sticking them on the measured object; Do I have to use speckle? Is there an alternative?

3.Why does the displacement formed in step2 have no practical significance? What is the specific result of step2? Where to find the result file and what it means?
4. From 2d-dic to 3d-dic, is the triangulation principle applied? Is it possible to measure one more displacement in the z direction? Is it possible to get the coordinates of the pixel in the three-dimensional space and draw the motion track of the object in the three-dimensional space coordinates?
thanks，
susan

**Comment by danasolav** [comment]
Thanks susan.
I'll try to answer your questions:
1. Currently the toolbox supports checkerboard target for distortion correction and a 3D calibration object (such as a cylinder with a dot pattern) for stereo calibration. In order to perform stereo calibration with only with a checkerboard, quite a lot of modifications to the codes are required. I'm currently working on an extension to the toolbox that will allow that for systems with 2 cameras, but it's not ready for publication yet.

2. The speckle pattern can be applied manually. Just try to make sure for optimum results that the black vs white distribution is roughly 50%. What is your application? Normally you'd want the speckled pattern to be on the surface that you measure and not on paper. Can you briefly describe your setup?

3. The displacements in step2 are pixel displacements on the original images, and they don't have physical meaning until they're transformed into points in 3D space with units of length in step3.

4. Yes. The triangulation principle is applied in step3 to transform image points to 3D points. The toolbox doesn't allow the plotting of tracking of a point, but you can easily do it yourself. If you know the index of the point you want to track, you can find its x,y,z displacements. However, if your goal is to track displacements of a rigid body, and you don't care about deformations/strains, I think this toolbox is not what you're looking for. There are other, more simple, tools for rigid body motion tracking. This package is tailored for measuring strains, and specifically on surfaces that require multiple cameras.

Let me know if you have any further questions,
Dana

**Comment by shanchao0906** [comment]
Hi Dana,
Thank you very much for your answer. I am very sorry for replying you so late.
I basically want to use this toolbox to track the three-dimensional motion of a point on the surface of an object.But I had some problems with this toolbox.
1.I used a checkerboard with seven rows and nine columns,but toolbox reminds me to use the checkerboard with odd rows and even columns,otherwise I might get an error.so is there a big error?
2.Where is the origin of the world coordinate system?
3.I used a pair of stereo cameras and wanted to use the triangulation principle to obtain 3d spatial coordinates. When determining ROI in step2, I determined an ROI in the first frame of the reference camera. Is this right? Don't deformable cameras need to determine ROI?
4.Obtain a mat file in ROI in step2, where 1 represents inside ROI and 0 represents outside ROI. Obtain the mat file of 3d spatial coordinate points in step3, are these 3d spatial coordinate points one-to-one corresponding to the coordinates of pixel points in ROI?
But the number of 1's in the ROI that I deal with is different from the number of coordinate points in 3d space
So I wonder if there's a relationship between the two
Can you map the resulting three-dimensional space coordinates to the pixel coordinates on the image?
Thank you very much
susan

**Comment by shanchao0906** [comment]
Sorry, one more question

5. What is the influence of the measurement error of the cylinder in stereo calibration on the result

**Comment by danasolav** [comment]
Hi Susan,

1. Indeed the checkerboard has to be asymmetric, otherwise the points won't be detected correctly. See the instruction on "Prepare the Checkerboard Pattern" in this [link](https://www.mathworks.com/help/vision/ug/stereo-camera-calibrator-app.html#).

2. The origin of the world coordinate system is at the origin of your 3D calibration object (cylinder?). Since you provide the coordinates of the dots on your calibration object, you can control where the origin is.

3. That's correct. The ROI has to be selected only on the first image, and it's automatically detected in the rest of the images.

4. The 3D coordinates generated in step 3 correspond to the 2d pixel coordinates generated in step 2, but not to the ROI. The points depend on the subset spacing you select in Ncorr.

5. I'm not sure understand this question. If there are errors in the calibration they will propagate to the final measurement, but there might be additional errors due to the matching in step2 which depend on your speckle pattern quality, lighting, etc.

Thanks,
Dana
