### ISSUE TITLE
Calibration object and Speckled Object

### ISSUE THREAD

**Issue by fikreej** [MultiDIC/MultiDIC#18]
hi, i'm doing something similar to this for my final year project.
but i'm having prob with the calibration object n speckled object pattern which i'm not sure to print. 
was it on a A4 size sticker paper and what software used to generate the pattern for both object.
Thank you.

**Comment by danasolav** [comment]
In the sample data they were printed on adhesive paper which you can use in a regular printer.

For the calibration object, check out the function `generate_cylindrical_calibration_object_coordinate_file.m` in the lib_MultiDIC folder.

For the speckle pattern, you should apply it directly on the object you want to test. In the sample data it was printed because only a rigid body motion was applied for the test, but generally for measuring strain it should be applied to the surface using for example spray paint, airbrush, or even manually with a sharpie, depends on the material and the size you need.

Thanks,
Dana

**Comment by fikreej** [comment]
Ohhhhh thats solved my prob . Thank you Dana for the respond . Another thing , how do you assess all the camera from a pc ? Do you enable ssh on all pi zerow ?
