### ISSUE TITLE
Stitching process

### ISSUE THREAD

**Issue by fikreej** [MultiDIC/MultiDIC#20]
Hello Dana , when i run step three for pair 1 (cam 1,2) and pair 3(cam2,3) , the stiching process came out weird where did not stitch together

**Comment by danasolav** [comment]
I apologize, the stitching algorithm is still a little buggy. Can you send me your files you used so that I can recreate the error and try to debug it?
In the meantime I can recommend that you skip the stitching process in Step 3 and proceed without stitching. If you need to stitch the surfaces you could do it outside MultiDIC using software like MeshLab (free) or RhinoCeros (better but expensive).

Thanks,
Dana
