### ISSUE TITLE
some questions about MultiDIC

### ISSUE THREAD

**Issue by JackLilianjie** [MultiDIC/MultiDIC#7]
Hi, Dana
   First of all, I am very grateful for the toolbox you provided. It seems very attractive.But when I try to run the toolbox using the provided sample_data, I have a few doubts,could you do me a favor and answer my doubts:
  1 where is the exact position and orientation of the world coordinate system of step4 results? is the Cylinder bottom  the X-Y plane?  then where is the X axis？
  2 If  step0 is skipped, can step 1 determine both  internal parameters(focal length etc)external parameters?
 3 When I look the step4 results, I found that the number of points3D is 4864 and the faces is 9614. I don't understand how this is going on? Do the points3D mean the center of the subset? what about the faces results?
 I will look forward to your reply.thanks you in advance！
Yours
jack

**Comment by danasolav** [comment]
Hi Jack,
Thanks for the feedback.
1. The world coordinate system is defined by the calibration object. In the sample_data the origin is on the axis of the cylinder at the height of the lowest row of dots, and the positive x direction is pointing to the first column of dots. You can visualize it by running STEP1p or by running this short code when you have the coordinates mat file in your workspace:
```
cFigure; hold on;
for ir=1:size(P3d,1)
    for ic=1:size(P3d,2)
        plotV(P3d(ir,ic,:),'o');
        text(P3d(ir,ic,1),P3d(ir,ic,2),P3d(ir,ic,3),['(' num2str(ir) ',' num2str(ic) ')']);
    end
end
axisGeom;
```
2. The DLT parameters include both the intrinsic and extrinsic parameters, which are both required to establish the transformation from image positions to world 3D positions. However, the intrinsics and extrinsics are mixed inside the 11 DLT parameters, so you cannot explicitly extract the intrinsic parameters from it.
3. The points are the centers of the subsets which are then transformed to 3D using the calibration parameters. The faces are the triangular elements that form the mesh, and on which the strains and deformation are calculated. That's why the number is not the same. Each triangular face has 3 vertices which are the 3D points, and vertices are shared between triangles. I think Figure 4 in the following paper visualizes it pretty well:
[https://engrxiv.org/rejcn/](url)
Each row in the "Faces" field represents one triangle, and its 3 values are the indices of its 3 vertices. The 3D positions of these vertices are stored in the "Points3D" field.

Best,
Dana

**Comment by JackLilianjie** [comment]
Hi, Dana
Thank you very much for answering my questions. After carefully examining the step4's  results, I understand those questions.I get some new questions to ask you now.

 1. Does multiDIC Calculate the triangular face strain use the point data of 3 vertices ?
 2. How can I get NORMAL_STRAIN_X,NORMAL_STRAIN_Y and the SHEAR_STRAIN_XY from step4 ? I can 
    only find principal values and directions of strain in the final results.
 3. Do I have to manufacture a cylindrical or semi-cylindrical calibration object for the stereo calibration? 
    For example , If I only use a pair of cameras, can I use a flat object (a flat board maybe) with black 
    control points over white background instead of a cylindrical one?
I am looking forward to your reply.
Best,
Jack

**Comment by danasolav** [comment]
1. Yes, a 3D strain tensor is calculated for each triangle based on its 3 vertices. Unlike some other DIC software, there is no "strain window" which takes into account further points for strain calculation.
2. From the 3 vertices, the deformation tensor **F** is calculated, and from **F** the rest of the strain tensors are derived (see paper for details). strain like e_xx and e_yy are not relevant in the general 3D case because there is no planar coordinate system attached to each point or element. The strain tensors are defined in the global (world) system. The principal strains are both on the plane of the triangle, because the strain in the direction perpendicular to the plane of the triangle is always zero (cannot be measured). If you want to extract strain components in specific directions, you can extract them using the strain tensor (e.g. Deform.Emat) and the direction normal to the triangle plane (Deform.d3). However, you'll have to code it yourself, as this is not offered by the toolbox. For example, if the object is a cylinder you could define the local x as tangential and the local y as axial and then your NORMAL_STRAIN_Y will simply be the (3,3) component of the strain tensor (because z is the axial direction of the cylinder in the example), and to find NORMAL_STRAIN_X you'll have to multiply the strain tensor by the local tangential direction.
For general 3D bodies which are not planar or cylindrical, there is no unique definition for this coordinate system, that's why these values are not stored.
3. Yes. You have to manufacture your own object. The easiest way is to buy an accurate cylinder, print a dot grid on adhesive paper and carefully stick it on the cylinder, and measure its diameter using a caliper.
At the moment the toolbox can only be used with this kind of calibration object, but I'm working on adding an option to calibrate a system of two cameras using only the checkerboard (the same one that's used for step 0). I expect this addition to be released in a couple of months.

**Comment by JackLilianjie** [comment]
Hi,Dana
Thank you very much for your patient answer! I think that would help me a lot to understand this excellent toolbox.
Best!
Jack

**Comment by vasquezCamila** [comment]
Hi, Dana.
I'm getting some trouble by running the Step3 of your sample data. I just select the file "DIC2DpairResults" e than "DLTstruct" from both cameras, i got this error:

"Error using Load
Unabled to read file"

"Error in STEP3_3Dreconstruction (line 36)
    DLTstructTemp=load(DLTpath{ic});"
